apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: activity-1b
spec:
  template:
    metadata:
      labels:
        app: activity-1b
    spec:
      containers:
        - name: activity-1b
          image: nginx:1.155-alpine
          ports:
            - containerPort: 80
              hostPort: 8001
              