apiVersion: v1
kind: Pod
metadata:
  name: activity-3
  labels:
    name: activity-3
spec:
  containers:
  - name: activity-3
    env:
    - name: CONTENTS #Note: This app needs “CONTENT” environment variable to run
      value: "Hello from the environment"
    image: ravirdv/http-responder # this image starts a http responder listening on container port 5000
    ports:
    - containerPort: 5000
      hostPort: 3000
