#apiVersion: v1
#kind: Secret
#metadata:
#  name: api-token
#type: Opaque
#data:
#  AUTH_TOKEN_VALUE: this_is_nuclear_launch_code
---
apiVersion: v1
kind: Pod
metadata:
  name: activity-4
  labels:
    name: activity-4
spec:
  containers:
  - name: activity-4
    env:
    - name: CONTENT
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: AUTH_TOKEN_VALUE
    image: ravirdv/http-responder