apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  version: "1.0"
---
apiVersion: v1
kind: Pod
metadata:
  name: activity-4
  labels:
    name: activity-4
spec:
  containers:
  - name: activity-4
    env:
    - name: CONTENT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: version
    image: ravirdv/http-responder
    