apiVersion: v1
kind: Pod
metadata:
  name: activity-6
  labels:
    name: activity-6
spec:
  containers:
  - name: activity-6
    image: jetbrainsinfra/nginx-tcp-proxy
    env:
      - name: LISTEN_PORT
        value: "9000"
      - name: BACKEND_HOST
        value: "towel.blinkenlights.nl"
      - name: BACKEND_PORT
        value: "23"
    ports:
    - containerPort: 9000
      hostPort: 2000