apiVersion: v1
kind: Pod
metadata:
  name: activity-6
  labels:
    name: activity-6
spec:
  containers:
  - name: activity-6
    image: networkstatic/star_wars
    ports:
    - containerPort: 22
      hostPort: 6000
