version: '2.3'
services:
  server:
    image: rancher/k3s:v0.4.0-rc3
    command: server --disable-agent --kubelet-arg="address=0.0.0.0"
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-config:/output
    cpu_count: 1
    mem_limit: 500m
  node:
    image: rancher/k3s:v0.4.0-rc3
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
    cpu_count: 1
    mem_limit: 500m
  usersandbox:
    image: darshandkd/usersandbox:latest
    volumes:
    - k3s-config:/tmp/
    ports:
    - "5000:22"

volumes:
  k3s-config: {}
