version: '3.4'
services:
  server:
    image: rancher/k3s:v0.2.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - type: bind
      source: k3s-config
      target: /output

  node:
    image: rancher/k3s:v0.2.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c


  usersandbox:
    image: darshandkd/usersandbox:latest
    volumes:
    - type: bind
      source: k3s-config
      target: /tmp/
    ports:
    - "5000:22"

volumes:
  k3s-config: {}
